POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo Evento 2",
  "details": "Um evento para reunir a comunidade de desenvolvedores",
  "maximumAttendees": 1
}

###
POST http://localhost:3333/events/28684a83-ebcb-4681-b5e9-611a246a01a9/attendees
Content-Type: application/json

{
  "name": "Luiz Gustavo",
  "email": "luizsmatos3@gmail.com"
}

###
GET http://localhost:3333/events/28684a83-ebcb-4681-b5e9-611a246a01a9

###
GET http://localhost:3333/attendees/1/badge

###
GET http://localhost:3333/attendees/2/check-in

###
GET http://localhost:3333/events/28684a83-ebcb-4681-b5e9-611a246a01a9/attendees?query=silva